# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNhDQCjsLODlkGieRGP2x1TuoxqiFj0h

# Task
load this

Here is all the data you need:
"train.csv"

## Data loading

### Subtask:
Load the provided CSV file "train.csv" into a pandas DataFrame.

**Reasoning**:
Load the provided CSV file "train.csv" into a pandas DataFrame and display the first few rows.
"""

import pandas as pd

try:
    df_train = pd.read_csv('train.csv')
    display(df_train.head())
except FileNotFoundError:
    print("Error: 'train.csv' not found. Please ensure the file exists in the current directory.")
except Exception as e:
    print(f"An error occurred: {e}")

"""## Summary:

### 1. Q&A

No questions were posed in the provided data analysis task.


### 2. Data Analysis Key Findings

* The `train.csv` file was successfully loaded into a pandas DataFrame named `df_train`.
* The DataFrame preview shows columns including 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', and 'Embarked'.


### 3. Insights or Next Steps

* Explore the data further by examining data types, summary statistics, and missing values in `df_train`.
* Visualize the data to identify potential patterns and relationships between variables.

"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv("train.csv")

df.head(5)
## Display the first few rows of the dataset

df.columns

# Check the dimensions of the dataset
df.shape

# Get summary statistics of numerical variables
df.describe()

"""In the training set:

38.3% people survived
More number of people were actually in 3rd class
50% of passengers were in between the age of 20 to 38
Since the survival rate is 0.38, even if I decide to give a submission of all passengers being perished, I would still be having a accuracy of 62%. So accuracy cannot be considered as the only measure in saying how good the model is.
"""

# Check the data types of variables
df.dtypes

#Find the duplicates

df.duplicated().sum()

# Check for missing values
df.isnull().sum()

df.info()

"""It indicates that there are total of 891 passesnger details among which 177 people's Age is missing and 687 people's Cabin details are missing. And 2 people's Embarkation details are missing."""

df.drop(["PassengerId",'Cabin'],axis = 1,inplace = True)

df.shape

df.columns

#now let us find out the average fare people paid to get onto titanic and the average age of passengers that boarded
print("Average Fare: ",round(df['Fare'].mean(),3))
print("Average Age: ",round(df['Age'].mean(),2))

# Bar plot
sns.countplot(x='Survived', hue='Survived', data=df)
plt.xlabel('Survival Status')
plt.ylabel('Count')
plt.title('Survival Count')
plt.show()

df.groupby(['Survived','Sex'])['Survived'].count()

pd.crosstab(df.Pclass, df.Survived, margins=True)

df[df['Pclass'] == 1].Survived.groupby(df.Survived).count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.axis('equal')
plt.legend(["Perished","Survived"])
plt.title("First class survival rate")
plt.show()

df[df['Pclass'] == 2].Survived.groupby(df.Survived).count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.axis('equal')
plt.legend(["Perished","Survived"])
plt.title("Second class survival rate")
plt.show()

df[df['Pclass'] == 3].Survived.groupby(df.Survived).count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.axis('equal')
plt.legend(["Perished","Survived"])
plt.title("Third class survival rate")
plt.show()

sns.countplot(x=df['Pclass'],hue=df['Survived'])
plt.title=("Class wise survival")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

sns.countplot(x='Survived', data=df,hue = 'Embarked');

pd.crosstab([df.Sex, df.Survived], df.Pclass, margins=True)

pd.crosstab([df.Sex, df.Survived], [df.SibSp, df.Pclass], margins=True)

#The above crosstab indicates 2 things:

#Most of the passengers didn't have siblings onboard and the majority had atmost 1 sibling onboard

#Not much of priority was given to the passengers who had siblings onboard in the rescue operation

pd.crosstab([df.Sex, df.Survived], [df.Parch, df.Pclass], margins=True)

#The above crosstab indicates 2 things:

#Most of the passerenges didn't have parents onboard and the majority had atmost 1 parent onboard
#Not much of priority was given to the passengers who had parents onboard in the rescue operation

sns.barplot(y = "Fare",x = "Pclass",data = df,hue=df['Survived'])

sns.swarmplot(x='Survived', y='Fare', data=df,hue='Survived');

sns.boxplot(y = "Fare",x = "Pclass",data = df[df["Fare"] < 200],hue='Pclass')

sns.barplot(y = "Fare",x = "Pclass",data = df[df["Fare"] < 200],hue='Pclass')

sns.pairplot(df.drop("Name",axis = 1).dropna(),hue = "Survived")

#Now lets see how we can handle the missing values of Age

#By filling with mean value i.e, df.fillna(value = df.mean())
#By filling mean value of corresponding Survived category

df.groupby('Survived').describe()['Age']

"""Both values actually look very similar

Now let's try something special. If we see the name column, there is data which corresponds to the age of the person. Yes: Mr. Mrs. Master. Miss. So lets use that in filling the NA values for age
"""

df.head(5)

def extract(x):
    temp = x.split(" ")
    if "Mr." in temp:
        return "Mr"
    elif "Mrs." in temp:
        return "Mrs"
    elif "Miss." in temp:
        return "Miss"
    elif "Master." in temp:
        return "Master"
    elif "Dr." in temp:
        return "Dr"
    else:
        return None

df["Category"] = df["Name"].apply(extract)

df.head()

df["Category"].unique()

print("Mr." , np.mean(df[df["Category"] == "Mr"]["Age"]))
print("Mrs." , np.mean(df[df["Category"] == "Mrs"]["Age"]))
print("Miss." , np.mean(df[df["Category"] == "Miss"]["Age"]))
print("Master." , np.mean(df[df["Category"] == "Master"]["Age"]))
print("Dr." , np.mean(df[df["Category"] == "Dr"]["Age"]))

#This should be a better approach to fill the missing values of Age column

# Histogram
df.hist(column='Age', bins=80)
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Distribution of Age')
plt.show()

# Scatter plot
plt.scatter(df['Age'], df['Fare'])
plt.xlabel('Age')
plt.ylabel('Fare')
plt.title("Age vs. Fare")
plt.show()

# Box plot
sns.boxplot(x=df['Survived'], y=df['Fare'])
plt.xlabel('Survival Status')
plt.ylabel('Fare')
plt.title('Survival Status vs. Fare')
plt.show()

# Correlation analysis
correlation = df[['Age', 'Fare']].corr()
print(correlation)

# Cross-tabulation
cross_tab = pd.crosstab(df['Pclass'], df['Survived'])
print(cross_tab)

# Histogram
df.hist(column='Fare', bins=200)
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.title('Distribution of Fare')
plt.show()

survived_above_500=((df['Fare']>500)&(df['Survived']==1)).sum()
print("Survived After Paying more than 500 dollars: ", survived_above_500)

df.loc[df['Fare']>500]

male_dead=((df['Sex']=='male')&(df['Survived']==0)).sum(0)
print("Male Dead: ",male_dead)
male_survived=((df['Sex']=='male')&(df['Survived']==1)).sum(0)
print("Male Survived: ",male_survived)

female_dead=((df['Sex']=='female')&(df['Survived']==0)).sum(0)
print("Female Dead: ",female_dead)
female_survived=((df['Sex']=='female')&(df['Survived']==1)).sum(0)
print("Female Survived: ",female_survived)

#now we will be plotting a bar graph depicting the values we calculated above
m_data=(male_dead,male_survived)
f_data=(female_dead,female_survived)
index=['Dead','Survived']
p1=plt.bar(np.arange(len(m_data)),m_data,color='blue')
p2=plt.bar(np.arange(len(f_data)),f_data,bottom=m_data,color='orange')
plt.xticks(np.arange(len(m_data)),index)
plt.legend((p1[0],p2[0]),('Male','Female'))
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Gender Wise Survival')
plt.show()

sns.countplot(x=df['Embarked'],hue=df['Embarked'])
plt.title="Embarked wise Count"
plt.xlabel("Port")
plt.ylabel("Count")
plt.show()

sns.countplot(x=df['Embarked'],hue=df['Survived'])
plt.title="Embarked wise survival"
plt.xlabel("Port")
plt.ylabel("Count")
plt.show()

#let us now create a heatmap
ax= sns.heatmap(df.corr(), annot=True)
plt.show()

#let us now create a heatmap
# Exclude non-numeric columns from correlation calculation
numerical_df = df.select_dtypes(include=['number'])
ax = sns.heatmap(numerical_df.corr(), annot=True)
plt.show()

#let us now convert categorical values to integer values
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})

numerical_df = df.select_dtypes(include=['number'])
ax = sns.heatmap(numerical_df.corr(), annot=True)
plt.show()

fig, ax = plt.subplots(3,3,figsize=(16,16))

#The number of fatalities is greater than the number of survivors.
sns.countplot(x = 'Survived',data=df,ax=ax[0][0], palette='viridis')

#The majority of passengers were in economy class 3, and luxury class 1 had the fewest passengers
sns.countplot(x = 'Pclass',data=df,ax=ax[0][1], palette='pastel')

#According to this chart, it is clear that the number of male passengers is greater than the number of female passengers,
#and this difference may affect the survival rate
sns.countplot(x = 'Sex',data=df,ax=ax[0][2], palette='Set2')

#Most passengers traveled on the Titanic without siblings, brothers, or spouses.
#A small number traveled with 1 or 2 companions, and the number of people with 3 or more companions is rarely seen.
sns.countplot(x = 'SibSp',data=df,ax=ax[1][0], palette='Blues')

#The majority of passengers traveled without parents or children
sns.countplot(x = 'Parch',data=df,ax=ax[1][1], palette='coolwarm')

#From which ports have most passengers boarded?
sns.countplot(x = 'Embarked',data=df,ax=ax[1][2], palette='Set3')


#According to the related chart, it can be inferred that the ticket fare for most passengers is below 50
#units of currency (for example, pounds)
sns.distplot(df['Fare'], kde=True, ax=ax[2][1])


#The age distribution follows a bell-shaped curve, with the majority of passengers concentrated around the age of 30.
#Only a small proportion of passengers are older than the mean, with relatively few individuals exceeding the age of 60.
sns.distplot(df['Age'], kde=True, ax=ax[2][2])

#This chart shows that most passengers traveled alone, and fewer had companions.
#sns.countplot(x = 'Alone',data=df,ax=ax[2][0], palette='cubehelix')

plt.tight_layout()